site_name: DeviceConnect Users
theme: 'readthedocs'
remote_branch: 'master'
pages:
- 'Top': 'index.md'
- 'DeviceConnectについて': 'about.md'
- 'はじめてみよう（Android）': 'getting-started/android.md'
- 'はじめてみよう（iOS）': 'getting-started/ios.md'
- '対応デバイスについて': 'support-devices.md'
- '利点&欠点': 'pros-cons.md'