site_name: DeviceConnect Users
theme: 'readthedocs'
remote_branch: 'master'
google_analytics: ['UA-79831666-1', 'deviceconnectusers.github.io']
pages:
- 'Top': 'index.md'
- 'DeviceConnectについて': 'about.md'
- 'Android':
  - 'はじめてみよう': 'android.md'
  - 'DeviceConnectManagerについて': 'android/device_connect_manager.md'
  - 'プラグインをビルドする': 'android/plugin.md'
  - 'Pebbleプラグイン': 'android/plugins/pebble.md'
- 'はじめてみよう（iOS）': 'ios.md'
- 'はじめてみよう（JavaScript）': 'javascript.md'
- 'Web API':
  - 'Web APIについて': 'webapi.md'
  - 'WebSocket/イベント通知について': 'webapi/websocket.md'
  - 'エラーについて': 'webapi/error.md'
  - 'スコープについて': 'webapi/scope.md'
  - 'バイブレーションAPI': 'webapi/vibration.md'
- '対応デバイスについて': 'support-devices.md'
- '利点&欠点': 'pros-cons.md'

